version: '3.7'

services:
  tg-bot:
    build: .
    container_name: tg_bot
    restart: always
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: python scheme_bot.py