name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout selected branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files to remote server
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ user1@82.202.158.156:/opt/containers/bot

      - name: Deploy using docker-compose
        run: |
          ssh -o StrictHostKeyChecking=no user1@82.202.158.156 << 'EOF'
            cd /opt/containers
            sudo docker compose pull
            sudo docker compose down
            sudo docker compose up -d
          EOF
